name: Build executables

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  test:
    uses: ./.github/workflows/_run-tests.yml

  build:
    needs: test
    uses: ./.github/workflows/_build-artifacts.yml
